version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/docker/nginx.conf:/etc/nginx/nginx.conf
    links:
      - backend
  #     - frontend

  redis:
    image: redis:alpine

  workers:
    build: 
      context: ${PWD}/docker
      dockerfile: worker-dockerfile
    volumes:
      - ${PWD}/worker.py:/app/worker.py
    links:
      - redis

  backend:
    build: 
      context: ${PWD}/docker
      dockerfile: backend-dockerfile
    ports:
      - "8080"
    volumes:
      - ${PWD}/webservice:/app
    links:
      - redis

  frontend:
    build:
      context: ${PWD}/docker
      dockerfile: frontend-dockerfile
    ports:
      - "8090:8080"
    volumes:
      - ${PWD}/frontend:/usr/src/app
